### ISSUE TITLE
BLDSS::Config getCredentials not used

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/koha-ill-bldss#3]
It looks like the plan was to optionally allow for per branch BLDSS accounts.  The getCredentials method on the BLDSS::Config object expected a `<credentials>` block at the top level of the xml config. This contained the api key, auth, id etc. One could then optionally have further per branch `<credentials>` blocks in each branch. If a branch-specific one was present then it would be used for setting up the api connection for particular requests, otherwise it would fall back to the top level shared credentials.

This functionality depended on some code getting into community IllRequest.pm which added the passing of branchcodes during request creation. This functionality was never written and as such the feature didn't reach fruition. 

The getCredentials call eventually become orphaned and a set of top level `<api_*>` blocks were added to the XML as a replacement for the `<credentials>` block.

**Comment by AndrewIsh** [comment]
This now is used and enables the per branch credentials: https://github.com/PTFS-Europe/koha-ill-bldss/commit/55b7c221116eb4a2e7ea463f5a167eec719f6a60 It turned out that it was possible to achieve without touching core Koha.

Closing.
